### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by dbdante** [RUB-SysSec/nyx-net#2]
Appreciate releasing source code for this significant work.  I can see packer is doing some of the work when preparing the VM. Are there step by step instructions/tutorial on setting up a new target, creating agent, IPC spec for agent and host communication, using packer etc. Please point to any reference you can if there are no documentation currently. Thanks

**Comment by schumilo** [comment]
Thanks for feedback! 
Unfortunately, we do not yet have complete documentation on all features of the packer. This is something we will provide in the near future. 
Other than that, we cannot provide any details on IPC-fuzzing yet (for obvious reasons).
